RegistryTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAYPERREQUEST
    AttributeDefinitions:
      - AttributeName: node_id
        AttributeType: S
      - AttributeName: path
        AttributeType: S
    KeySchema:
      - AttributeName: node_id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: path-index
        KeySchema:
          - AttributeName: path
            KeyType: HASH
        Projection:
          ProjectionType: ALL

